#include <stdexcept>


int main() {
    throw std::runtime_error("Boom!");
    return 0;
}
